# Generated by Django 3.1 on 2023-04-06 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_reviewrating_product_remove_reviewrating_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='drink_description',
            new_name='description',
        ),
    ]
