# Generated by Django 3.1 on 2023-04-06 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_variation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Variation',
        ),
    ]
